openapi: '3.0.0'
info:
  tittle : 'Movie-api'
  description: "API documentation for Movie-api"
  version: '1.0.0'

  servers:
    url: `http://localhost:5000`
    description: 'Dev environment'

Schemes: [HTTP,HTTPS]
Paths:
  /auth/register:
    post:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  
